### ISSUE TITLE
Doesn't work with ember-cli 1.13.8

### ISSUE THREAD

**Issue by DLiblik** [minichate/ember-cli-conditional-compile#6]
I get the following error at run-time: Uncaught ReferenceError: ```EMBER_CLI_CONDITIONAL_COMPILE_INJECTIONS is not defined.```

I also receive the ```Could not find any feature flags.You may need to add them in your config/environment.js``` message on compilation.  

Here is my code:

```
module.exports = function(environment) {
    var ENV = {
        // Testing...
        featureFlags: {
            ENABLE_FOO: true
        },

        includeDirByFlag: {
            ENABLE_FOO: [/pods\/foos/, /pods\/foo/],
        },

...

    return ENV;
};

```

**Comment by minichate** [comment]
Thanks @DLiblik! I'll take a look at this over the weekend.

**Comment by jonesetc** [comment]
@minichate Any updates on this? This seems like it would be very handy to use, but we're on 1.13.8.

**Comment by jonesetc** [comment]
So, I went down the rabbit hole a little bit here. These issues look like they are because of this line:

https://github.com/minichate/ember-cli-conditional-compile/blob/253c47a7517afea4b2cdaf66b2ae49baa22cd929/index.js#L98

Which is not doing anything because at this point in the processing, there is no `app/` directory, instead it is the `my-app-name` directory. The simple fix to this is change that line to:

```js
files: [config.modulePrefix + '/initializers/ember-cli-conditional-compile-features.js', config.modulePrefix + '/initializers/conditional-compile.js'],
```

Past this however is another problem, otherwise I'd submit a PR for this right now. I'm not sure what the point of the helpers in: 

https://github.com/minichate/ember-cli-conditional-compile/blob/master/app/initializers/conditional-compile.js

It is using an old way of registering helpers, and throws this runtime error:

```
Uncaught TypeError: Ember.default.Handlebars.registerHelper is not a function
```

The new way for registering helpers can be found here:

http://emberjs.com/blog/2015/06/12/ember-1-13-0-released.html#toc_new-ember-js-helper-api

Like I said, I don't even know what these helpers are or what they were intended to do, so I'm not using them at all. When I comment out the whole body of this initializer or remove the file all together, everything works as expected.

**Comment by minichate** [comment]
@jonesetc Can you take a look at version 0.2.0 and see if that fixes the compatibility problem?

FYI; the Handlebars helper is so that you can use the flags within `.hbs` templates:

```handlebars
{{#if-flag-ENABLE_FOO}}
The FOO flag is enabled \o/
{{/if-flag-ENABLE_FOO}}
```

**Comment by andrewvy** [comment]
Hi, I've tried the above and this addon doesn't work on Ember 2.x versions because of the helpers.

I've tried looking into it, but I'm not totally sure on how to approach this issue because Ember wants helpers to be defined / exported. As in I'm not sure how to dynamically define the helpers like you're doing.. :)

**Comment by minichate** [comment]
@andrewvy You're right :) I was looking into this before, and there are some ideas floating around that we might be able to hook directly into the HTMLBars AST to remove the need for the helper method. That idea is currently just vapourware though.

If you want to create a new issue for Ember 2.x compatibility I'll try and keep my notes there
